### ISSUE TITLE
roadmap 🗺️

### ISSUE THREAD

**Issue by dudendy** [orden-gg/df0#4]
## contracts
- [x] `spaceType` perlin procgen
- [ ] basic planets implementation
- [ ] basic ships implementation 
- [ ] spawn
- [ ] move
- [ ] resources
- [ ] attack
- [ ] planets v2
- [ ] ships v2

## client-phaser
- [ ] client-side `spaceType` perlin procgen
- [ ] space terrain visualization
- [ ] draggable map
- [ ] ships visualization
- [ ] maps visualization

## client-three (WebGPU)
**TBD**
